# -*- coding: utf-8 -*-
"""garden.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ATydsQHcvysDrybr04HgDNYqZaHWR-i
"""

import spacy
nlp = spacy.load("en_core_web_sm")

# Garden path sentences are sentences that initially lead a reader to interpret them in one way,
# only to reveal a different structure upon further reading. This creates temporary confusion,
# making them useful for exploring how humans and machines process language.

gardenpathSentences = [
    "The Bible study Huei leads at dawn distracts the sleepy intern.",
    "The car Huei restored in Penang drives better than expected by mechanics.",
    "The marketing insights Huei shares on YouTube surprise the algorithm."
]

for sentence in gardenpathSentences:
    print(f"\nSentence: {sentence}")
    doc = nlp(sentence)

    print("Tokens:")
    for token in doc:
        print(f"  {token.text} ({token.pos_})")

    print("Named Entities:")
    for ent in doc.ents:
        print(f"  {ent.text} ({ent.label_}) - {spacy.explain(ent.label_)}")

# Optional: Explain entity types used
print("\nEntity Explanations:")
print("FAC:", spacy.explain("FAC"))
print("GPE:", spacy.explain("GPE"))
print("ORG:", spacy.explain("ORG"))

print("\nEntity Explanations:")
print("FAC:", spacy.explain("FAC"))
print("GPE:", spacy.explain("GPE"))

"""Entity Comments:

Garden path sentences are sentences that will initially lead a reader to interpret them in one way, then it will reveal a different structure as the leader continues reading.

1. ORG (Organisation) — This is used for companies, institutions, or groups.
   In "The marketing insights Huei shares on YouTube surprise the algorithm,"
   spaCy tagged "YouTube" as an ORG, and YouTube is a company, so the label is correct here too.

2. GPE (Geopolitical Entity) — This stands for places like countries, cities, or states. In the sentence "The car Huei restored in Penang drives better than expected by mechanics,". spaCy picked up "Penang" as a GPE. That makes sense as Penang is a real place in Malaysia, so the tag fits perfectly.
"""